### ISSUE TITLE
Support HipChat 2.0.0 build 2.0.7

### ISSUE THREAD

**Issue by eloo** [daneharrigan/hipchat#23]
It seems that the XMPP interface at port 5222/5223 will be closed with newer HipChat server versions.
Is der any idea how to support this change?

https://confluence.atlassian.com/hc/hipchat-server-release-notes-608731400.html

**Comment by daneharrigan** [comment]
This may take me a bit of time. I need to understand whats changed in 2.0. Thanks for bringing this to my attention @Eloo

**Comment by hrak** [comment]
There is not much you can do on the client side, since this change is implemented on the server using iptables rules. See https://confluence.atlassian.com/hipchatkb/external-xmpp-ports-5222-5223-disabled-by-default-in-hipchat-server-2-0-7-859442760.html for more info.

You can re-enable XMPP on the server with the command
```
hipchat network --enable-xmpp-ports
```

But they also state 'Future releases may not support direct XMPP access'.

**Comment by Eloo** [comment]
But it seems that XMPP could be used via BOSH 
```https://yourservername.domain/http-bind```
Or did I misunderstood this?
